export const data = [
	{
		img: "/top-creators/Avatar Placeholder.svg",
		name: "Keepitreal",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-1.svg",
		name: "DigiLab",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-2.svg",
		name: "GravityOne",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-3.svg",
		name: "Juanie",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-4.svg",
		name: "BlueWhale",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-5.svg",
		name: "mr fox",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-6.svg",
		name: "Shroomie",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-7.svg",
		name: "robotica",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-8.svg",
		name: "RustyRobot",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-9.svg",
		name: "animakid",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-10.svg",
		name: "Dotgu",
		sales: "34.53 ETH",
	},
	{
		img: "/top-creators/Avatar Placeholder-11.svg",
		name: "Ghiblier",
		sales: "34.53 ETH",
	},
];
